#!/bin/bash
# Compile GLSL → SPIR-V → embedded C header.
# Run from anywhere; emits tri_shaders.h next to this script.
set -euo pipefail
cd "$(dirname "$0")"

glslangValidator -V tri.vert  -o tri.vert.spv
glslangValidator -V tri.frag  -o tri.frag.spv
glslangValidator -V quad.vert -o quad.vert.spv
glslangValidator -V quad.frag -o quad.frag.spv

{
  echo "// Auto-generated by build_shaders.sh — do not edit."
  echo "// Source: tri.vert, tri.frag, quad.vert, quad.frag"
  echo "#ifndef TRI_SHADERS_H"
  echo "#define TRI_SHADERS_H"
  echo "#include <stdint.h>"
  echo "#include <stddef.h>"
  for stem in tri_vert tri_frag quad_vert quad_frag; do
    src="${stem/_/.}.spv"
    echo
    xxd -i -n "${stem}_spv" "$src" | sed 's/unsigned char/static const uint8_t/; s/unsigned int/static const size_t/'
  done
  echo
  echo "#endif"
} > tri_shaders.h

rm -f tri.vert.spv tri.frag.spv quad.vert.spv quad.frag.spv
echo "Wrote tri_shaders.h"
