#!/bin/bash
# Compile GLSL → SPIR-V → embedded C header.
# Run from anywhere; emits tri_shaders.h next to this script.
set -euo pipefail
cd "$(dirname "$0")"

SHADERS=(tri.vert tri.frag quad.vert quad.frag quad_tex.vert quad_tex.frag axes.vert axes.frag world.vert world.frag)
for s in "${SHADERS[@]}"; do glslangValidator -V "$s" -o "$s.spv"; done

{
  echo "// Auto-generated by build_shaders.sh — do not edit."
  echo "// Source: ${SHADERS[*]}"
  echo "#ifndef TRI_SHADERS_H"
  echo "#define TRI_SHADERS_H"
  echo "#include <stdint.h>"
  echo "#include <stddef.h>"
  for s in "${SHADERS[@]}"; do
    sym="${s/./_}"  # tri.vert -> tri_vert
    echo
    xxd -i -n "${sym}_spv" "$s.spv" | sed 's/unsigned char/static const uint8_t/; s/unsigned int/static const size_t/'
  done
  echo
  echo "#endif"
} > tri_shaders.h

for s in "${SHADERS[@]}"; do rm -f "$s.spv"; done
echo "Wrote tri_shaders.h"
