#!/usr/bin/env bash
# Folds the compiled game archives in LambdaVision/Vendor/libxash/games/
# (libgame-<gamedir>.a, from build_game.sh or a CI release) into libxash.a,
# which the app force-loads, and regenerates the compiled-games table
# (Lambda_CompiledGames, read by the engine and the app's library).
#
#   ./pack_libxash.sh             device: games/libgame-*.a      -> libxash.a
#   XR_SIM=1 ./pack_libxash.sh    simulator: games/libgame-*-sim.a -> libxash-sim.a
#
# Works on any libxash.a, a fresh local build or a released one: each game in
# games/ replaces that game's members in the archive, games already inside
# whose archive isn't in games/ stay, and the table lists whatever ends up
# inside, Half-Life first.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=xros_env.sh
. "$here/xros_env.sh"

lib="$LIBXASH_DIR/$ARCHIVE"
if [ ! -f "$lib" ]; then
    echo "No $ARCHIVE yet (build_xash_libxash.sh or fetch-prebuilts.sh makes it); the games stay in games/ until then."
    exit 0
fi

cd "$here"
if [ "${XR_SIM:-0}" = "1" ]; then
    rm -rf build/pack-sim
    mkdir -p build/pack-sim
    work="$here/build/pack-sim"
else
    rm -rf build/pack-device
    mkdir -p build/pack-device
    work="$here/build/pack-device"
fi
out="$work/$ARCHIVE"
cp "$lib" "$out"

has_member() { xcrun ar -t "$out" | grep -qx "$1"; }

games=()
for a in "$LIBXASH_DIR"/games/libgame-*.a; do
    [ -f "$a" ] || continue
    case "$a" in
        *-sim.a) [ "${XR_SIM:-0}" = "1" ] || continue ;;
        *) [ "${XR_SIM:-0}" = "1" ] && continue ;;
    esac
    games+=("$a")
done

for a in ${games[@]+"${games[@]}"}; do
    name="$(basename "$a" .a)"
    mkdir -p "$work/$name"
    (cd "$work/$name" && xcrun ar -x "$a")
    members=()
    while IFS= read -r m; do
        case "$m" in __.SYMDEF*) continue ;; esac
        members+=("$m")
        if has_member "$m"; then
            xcrun ar -d "$out" "$m"
        fi
    done < <(xcrun ar -t "$a")
    (cd "$work/$name" && xcrun ar -q "$out" "${members[@]}" 2>/dev/null)
    echo "  + $name"
done

if has_member lambda_compiled_games.o; then
    xcrun ar -d "$out" lambda_compiled_games.o
fi

# One registration record per game inside: lg_<gamedir>_entry.o defines
# lambda_game_entry_<gamedir>. Half-Life ("valve") first.
entries=()
while IFS= read -r m; do
    san="${m#lg_}"; san="${san%_entry.o}"
    if [ "$san" = valve ]; then entries=("$san" ${entries[@]+"${entries[@]}"}); else entries+=("$san"); fi
done < <(xcrun ar -t "$out" | grep -E '^lg_.+_entry\.o$' | sort)

table_c="$work/lambda_compiled_games.c"
{
    echo "// Generated by VisionPort/pack_libxash.sh: the games compiled into $ARCHIVE."
    echo "typedef struct { const char *gamedir, *dll, *title; } lambda_compiled_game_t;"
    for e in ${entries[@]+"${entries[@]}"}; do
        echo "extern const lambda_compiled_game_t lambda_game_entry_$e;"
    done
    echo "static lambda_compiled_game_t lambda_compiled_games[${#entries[@]} + 1]; // NULL-terminated"
    echo "__attribute__((constructor)) static void lambda_fill_compiled_games( void )"
    echo "{"
    i=0
    for e in ${entries[@]+"${entries[@]}"}; do
        echo "	lambda_compiled_games[$i] = lambda_game_entry_$e;"
        i=$((i + 1))
    done
    echo "}"
    echo "__attribute__((visibility(\"default\"))) const lambda_compiled_game_t *Lambda_CompiledGames( void )"
    echo "{"
    echo "	return lambda_compiled_games;"
    echo "}"
} > "$table_c"
xcrun clang --target="$CLANG_TARGET" -isysroot "$(xcrun --show-sdk-path --sdk "$SDK_NAME")" \
    -c "$table_c" -o "$work/lambda_compiled_games.o"
(cd "$work" && xcrun ar -q "$out" lambda_compiled_games.o 2>/dev/null)
xcrun ranlib -no_warning_for_no_symbols "$out" 2>/dev/null || xcrun ranlib "$out"

mv -f "$out" "$lib"
echo "Packed $ARCHIVE with compiled games: ${entries[*]:-none} ($(stat -f%z "$lib") bytes)"
